### ISSUE TITLE
About running error

### ISSUE THREAD

**Issue by MasterOfStar** [DrakenWan/DDOS_Detection#1]
Which version of sklearn do I need to use? In the latest version (1.0.2), it does not work.

```python test.py tcp_syn -1.5 1.0 2.0 1.0 1.0
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    tcp_syn_test(sys.argv[2:])
  File "test.py", line 18, in tcp_syn_test
    model = pickle.load(open("./saved_model/tcp_syn_data.sav", 'rb'))
ModuleNotFoundError: No module named 'sklearn.neighbors.classification'```

Can you give me a requirements.txt?

**Comment by Starkspider** [comment]
您好，您的邮件我已收到，我会尽快处理，谢谢！！！

**Comment by KartikayKaul** [comment]
Hi @MasterOfStar I am on this issue and resolve this ASAP.

**Comment by MasterOfStar** [comment]
> Hi @MasterOfStar I am on this issue and resolve this ASAP.

Thank you for your reply. I have solved the issue by trying to use the version of these dependencies as of April 2019.

python==3.6
matplotlib==3.0.3
numpy==1.19.5
pandas==0.24.2
scikit-learn==0.20.3
tqdm==4.31.1
And pickle is included on python

**Comment by KartikayKaul** [comment]
Glad to know you have resolved the issue. i understand the solution you
have come up with. However, I was thinking of trying to update the code to
save models using joblib. If I am able to run that successfully I will
update the repo.
